//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcomage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arcomage.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 Tower.
        /// </summary>
        public static string CardAmethystDescription {
            get {
                return ResourceManager.GetString("CardAmethystDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amethyst.
        /// </summary>
        public static string CardAmethystName {
            get {
                return ResourceManager.GetString("CardAmethystName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Tower, you lose 3 recruits, 2 damage to enemy Tower.
        /// </summary>
        public static string CardApprenticeDescription {
            get {
                return ResourceManager.GetString("CardApprenticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprentice.
        /// </summary>
        public static string CardApprenticeName {
            get {
                return ResourceManager.GetString("CardApprenticeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Tower &lt; enemy Tower, + 2 Tower, else +1 Tower.
        /// </summary>
        public static string CardBagOfBaublesDescription {
            get {
                return ResourceManager.GetString("CardBagOfBaublesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag of Baubles.
        /// </summary>
        public static string CardBagOfBaublesName {
            get {
                return ResourceManager.GetString("CardBagOfBaublesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +6 Recruits, +6 Wall, if Dungeon &lt; enemy Dungeon, +1 Dungeon.
        /// </summary>
        public static string CardBarracksDescription {
            get {
                return ResourceManager.GetString("CardBarracksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string CardBarracksName {
            get {
                return ResourceManager.GetString("CardBarracksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 Wall.
        /// </summary>
        public static string CardBasicWallDescription {
            get {
                return ResourceManager.GetString("CardBasicWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Wall.
        /// </summary>
        public static string CardBasicWallName {
            get {
                return ResourceManager.GetString("CardBasicWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7 Wall, 6 damage to enemy.
        /// </summary>
        public static string CardBattlementsDescription {
            get {
                return ResourceManager.GetString("CardBattlementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlements.
        /// </summary>
        public static string CardBattlementsName {
            get {
                return ResourceManager.GetString("CardBattlementsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 damage, 3 damage to your Tower.
        /// </summary>
        public static string CardBerserkerDescription {
            get {
                return ResourceManager.GetString("CardBerserkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berserker.
        /// </summary>
        public static string CardBerserkerName {
            get {
                return ResourceManager.GetString("CardBerserkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +6 Wall.
        /// </summary>
        public static string CardBigWallDescription {
            get {
                return ResourceManager.GetString("CardBigWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Wall.
        /// </summary>
        public static string CardBigWallName {
            get {
                return ResourceManager.GetString("CardBigWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players lose 8 bricks.
        /// </summary>
        public static string CardBrickShortageDescription {
            get {
                return ResourceManager.GetString("CardBrickShortageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick Shortage.
        /// </summary>
        public static string CardBrickShortageName {
            get {
                return ResourceManager.GetString("CardBrickShortageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 enemy Quarry.
        /// </summary>
        public static string CardCollapseDescription {
            get {
                return ResourceManager.GetString("CardCollapseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse!.
        /// </summary>
        public static string CardCollapseName {
            get {
                return ResourceManager.GetString("CardCollapseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Quarry &lt; enemy Quarry, Quarry = enemy Quarry.
        /// </summary>
        public static string CardCoppingTheTechDescription {
            get {
                return ResourceManager.GetString("CardCoppingTheTechDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copping the Tech.
        /// </summary>
        public static string CardCoppingTheTechName {
            get {
                return ResourceManager.GetString("CardCoppingTheTechName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enemy Wall &gt; 0, 10 damage, else 7 damage.
        /// </summary>
        public static string CardCorrosionCloudDescription {
            get {
                return ResourceManager.GetString("CardCorrosionCloudDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrosion Cloud.
        /// </summary>
        public static string CardCorrosionCloudName {
            get {
                return ResourceManager.GetString("CardCorrosionCloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 Tower, enemy loses 6 Bricks.
        /// </summary>
        public static string CardCrumblestoneDescription {
            get {
                return ResourceManager.GetString("CardCrumblestoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crumblestone.
        /// </summary>
        public static string CardCrumblestoneName {
            get {
                return ResourceManager.GetString("CardCrumblestoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +11 Tower, -6 Wall.
        /// </summary>
        public static string CardCrystallizeDescription {
            get {
                return ResourceManager.GetString("CardCrystallizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystallize.
        /// </summary>
        public static string CardCrystallizeName {
            get {
                return ResourceManager.GetString("CardCrystallizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Magic, +3 Tower, +1 enemy Tower.
        /// </summary>
        public static string CardCrystalMatrixDescription {
            get {
                return ResourceManager.GetString("CardCrystalMatrixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Matrix.
        /// </summary>
        public static string CardCrystalMatrixName {
            get {
                return ResourceManager.GetString("CardCrystalMatrixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7 Wall, gain 7 Gems.
        /// </summary>
        public static string CardCrystalRocksDescription {
            get {
                return ResourceManager.GetString("CardCrystalRocksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Rocks.
        /// </summary>
        public static string CardCrystalRocksName {
            get {
                return ResourceManager.GetString("CardCrystalRocksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Tower, +3 Wall.
        /// </summary>
        public static string CardCrystalShieldDescription {
            get {
                return ResourceManager.GetString("CardCrystalShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Shield.
        /// </summary>
        public static string CardCrystalShieldName {
            get {
                return ResourceManager.GetString("CardCrystalShieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +15 Tower.
        /// </summary>
        public static string CardDiamondDescription {
            get {
                return ResourceManager.GetString("CardDiamondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string CardDiamondName {
            get {
                return ResourceManager.GetString("CardDiamondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 damage to all Tower, all player&apos;s Magic -1.
        /// </summary>
        public static string CardDiscordDescription {
            get {
                return ResourceManager.GetString("CardDiscordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string CardDiscordName {
            get {
                return ResourceManager.GetString("CardDiscordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 damage, enemy loses 10 Gems, -1 enemy Dungeon.
        /// </summary>
        public static string CardDragonDescription {
            get {
                return ResourceManager.GetString("CardDragonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string CardDragonName {
            get {
                return ResourceManager.GetString("CardDragonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20 Tower.
        /// </summary>
        public static string CardDragonsEyeDescription {
            get {
                return ResourceManager.GetString("CardDragonsEyeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon&apos;s Eye.
        /// </summary>
        public static string CardDragonsEyeName {
            get {
                return ResourceManager.GetString("CardDragonsEyeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20 Wall, +8 Tower.
        /// </summary>
        public static string CardDragonsHeartDescription {
            get {
                return ResourceManager.GetString("CardDragonsHeartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon&apos;s Heart.
        /// </summary>
        public static string CardDragonsHeartName {
            get {
                return ResourceManager.GetString("CardDragonsHeartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Wall, +1 Quarry.
        /// </summary>
        public static string CardDwarvenMinersDescription {
            get {
                return ResourceManager.GetString("CardDwarvenMinersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarven Miners.
        /// </summary>
        public static string CardDwarvenMinersName {
            get {
                return ResourceManager.GetString("CardDwarvenMinersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 damage, +3 Wall.
        /// </summary>
        public static string CardDwarvesDescription {
            get {
                return ResourceManager.GetString("CardDwarvesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarves.
        /// </summary>
        public static string CardDwarvesName {
            get {
                return ResourceManager.GetString("CardDwarvesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 to all player&apos;s Quarries.
        /// </summary>
        public static string CardEarthquakeDescription {
            get {
                return ResourceManager.GetString("CardEarthquakeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake.
        /// </summary>
        public static string CardEarthquakeName {
            get {
                return ResourceManager.GetString("CardEarthquakeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Wall &gt; enemy Wall, 6 damage to enemy Tower, else 6 damage.
        /// </summary>
        public static string CardElvenArchersDescription {
            get {
                return ResourceManager.GetString("CardElvenArchersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elven Archers.
        /// </summary>
        public static string CardElvenArchersName {
            get {
                return ResourceManager.GetString("CardElvenArchersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw 1 card, discard 1 card, play again.
        /// </summary>
        public static string CardElvenScoutDescription {
            get {
                return ResourceManager.GetString("CardElvenScoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elven Scout.
        /// </summary>
        public static string CardElvenScoutName {
            get {
                return ResourceManager.GetString("CardElvenScoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Tower.
        /// </summary>
        public static string CardEmeraldDescription {
            get {
                return ResourceManager.GetString("CardEmeraldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        public static string CardEmeraldName {
            get {
                return ResourceManager.GetString("CardEmeraldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Tower, +1 Dungeon.
        /// </summary>
        public static string CardEmpathyGemDescription {
            get {
                return ResourceManager.GetString("CardEmpathyGemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empathy Gem.
        /// </summary>
        public static string CardEmpathyGemName {
            get {
                return ResourceManager.GetString("CardEmpathyGemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 damage, play again.
        /// </summary>
        public static string CardFaerieDescription {
            get {
                return ResourceManager.GetString("CardFaerieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faerie.
        /// </summary>
        public static string CardFaerieName {
            get {
                return ResourceManager.GetString("CardFaerieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +6 Tower, 4 damage to enemy Tower.
        /// </summary>
        public static string CardFireRubyDescription {
            get {
                return ResourceManager.GetString("CardFireRubyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Ruby.
        /// </summary>
        public static string CardFireRubyName {
            get {
                return ResourceManager.GetString("CardFireRubyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player with lowest Wall are -1 Dungeon and 2 damage to Tower.
        /// </summary>
        public static string CardFloodWaterDescription {
            get {
                return ResourceManager.GetString("CardFloodWaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Water.
        /// </summary>
        public static string CardFloodWaterName {
            get {
                return ResourceManager.GetString("CardFloodWaterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Wall, +5 Tower.
        /// </summary>
        public static string CardFocusedDesignsDescription {
            get {
                return ResourceManager.GetString("CardFocusedDesignsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused Designs.
        /// </summary>
        public static string CardFocusedDesignsName {
            get {
                return ResourceManager.GetString("CardFocusedDesignsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +9 Wall, lose 5 Recruits.
        /// </summary>
        public static string CardForcedLaborDescription {
            get {
                return ResourceManager.GetString("CardForcedLaborDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Labor.
        /// </summary>
        public static string CardForcedLaborName {
            get {
                return ResourceManager.GetString("CardForcedLaborName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Wall = 0, +6 Wall, else +3 Wall.
        /// </summary>
        public static string CardFoundationsDescription {
            get {
                return ResourceManager.GetString("CardFoundationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundations.
        /// </summary>
        public static string CardFoundationsName {
            get {
                return ResourceManager.GetString("CardFoundationsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Wall, play again.
        /// </summary>
        public static string CardFriendlyTerrainDescription {
            get {
                return ResourceManager.GetString("CardFriendlyTerrainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Terrain.
        /// </summary>
        public static string CardFriendlyTerrainName {
            get {
                return ResourceManager.GetString("CardFriendlyTerrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 to all player&apos;s Dungeon, you gain 3 Recruits.
        /// </summary>
        public static string CardFullMoonDescription {
            get {
                return ResourceManager.GetString("CardFullMoonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Moon.
        /// </summary>
        public static string CardFullMoonName {
            get {
                return ResourceManager.GetString("CardFullMoonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 damage to enemy Tower.
        /// </summary>
        public static string CardGemSpearDescription {
            get {
                return ResourceManager.GetString("CardGemSpearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem Spear.
        /// </summary>
        public static string CardGemSpearName {
            get {
                return ResourceManager.GetString("CardGemSpearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 damage to enemy Tower.
        /// </summary>
        public static string CardGemstoneFlawDescription {
            get {
                return ResourceManager.GetString("CardGemstoneFlawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemstone Flaw.
        /// </summary>
        public static string CardGemstoneFlawName {
            get {
                return ResourceManager.GetString("CardGemstoneFlawName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 damage, +1 Gem.
        /// </summary>
        public static string CardGnomeDescription {
            get {
                return ResourceManager.GetString("CardGnomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        public static string CardGnomeName {
            get {
                return ResourceManager.GetString("CardGnomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 damage to enemy Tower, you take 1 damage.
        /// </summary>
        public static string CardGoblinArchersDescription {
            get {
                return ResourceManager.GetString("CardGoblinArchersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblin Archers.
        /// </summary>
        public static string CardGoblinArchersName {
            get {
                return ResourceManager.GetString("CardGoblinArchersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 damage, you take 3 damage.
        /// </summary>
        public static string CardGoblinMobDescription {
            get {
                return ResourceManager.GetString("CardGoblinMobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblin Mob.
        /// </summary>
        public static string CardGoblinMobName {
            get {
                return ResourceManager.GetString("CardGoblinMobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +15 Wall.
        /// </summary>
        public static string CardGreatWallDescription {
            get {
                return ResourceManager.GetString("CardGreatWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Wall.
        /// </summary>
        public static string CardGreatWallName {
            get {
                return ResourceManager.GetString("CardGreatWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +6 Wall, +3 Tower.
        /// </summary>
        public static string CardHarmonicOreDescription {
            get {
                return ResourceManager.GetString("CardHarmonicOreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic Ore.
        /// </summary>
        public static string CardHarmonicOreName {
            get {
                return ResourceManager.GetString("CardHarmonicOreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Magic, +3 Tower, +3 Wall.
        /// </summary>
        public static string CardHarmonicVibeDescription {
            get {
                return ResourceManager.GetString("CardHarmonicVibeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic Vibe.
        /// </summary>
        public static string CardHarmonicVibeName {
            get {
                return ResourceManager.GetString("CardHarmonicVibeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 damage, all players lose 5 Bricks, Gems and Recruits.
        /// </summary>
        public static string CardImpDescription {
            get {
                return ResourceManager.GetString("CardImpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp.
        /// </summary>
        public static string CardImpName {
            get {
                return ResourceManager.GetString("CardImpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 to all player&apos;s Quarries, you gain 4 Gems.
        /// </summary>
        public static string CardInnovationsDescription {
            get {
                return ResourceManager.GetString("CardInnovationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovations.
        /// </summary>
        public static string CardInnovationsName {
            get {
                return ResourceManager.GetString("CardInnovationsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +12 Tower, 6 damage to enemy.
        /// </summary>
        public static string CardLavaJewelDescription {
            get {
                return ResourceManager.GetString("CardLavaJewelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava Jewel.
        /// </summary>
        public static string CardLavaJewelName {
            get {
                return ResourceManager.GetString("CardLavaJewelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Tower &gt; enemy Wall, 8 damage to enemy Tower, else 8 damage.
        /// </summary>
        public static string CardLightningShardDescription {
            get {
                return ResourceManager.GetString("CardLightningShardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Shard.
        /// </summary>
        public static string CardLightningShardName {
            get {
                return ResourceManager.GetString("CardLightningShardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 damage to enemy Tower.
        /// </summary>
        public static string CardLittleSnakesDescription {
            get {
                return ResourceManager.GetString("CardLittleSnakesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little Snakes.
        /// </summary>
        public static string CardLittleSnakesName {
            get {
                return ResourceManager.GetString("CardLittleSnakesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Tower.
        /// </summary>
        public static string CardLodestoneDescription {
            get {
                return ResourceManager.GetString("CardLodestoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodestone.
        /// </summary>
        public static string CardLodestoneName {
            get {
                return ResourceManager.GetString("CardLodestoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Bricks, +2 Gems, play again.
        /// </summary>
        public static string CardLuckyCacheDescription {
            get {
                return ResourceManager.GetString("CardLuckyCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Cache.
        /// </summary>
        public static string CardLuckyCacheName {
            get {
                return ResourceManager.GetString("CardLuckyCacheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players lose 6 Recruits.
        /// </summary>
        public static string CardMadCowDiseaseDescription {
            get {
                return ResourceManager.GetString("CardMadCowDiseaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Cow Disease.
        /// </summary>
        public static string CardMadCowDiseaseName {
            get {
                return ResourceManager.GetString("CardMadCowDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Quarry.
        /// </summary>
        public static string CardMinersDescription {
            get {
                return ResourceManager.GetString("CardMinersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miners.
        /// </summary>
        public static string CardMinersName {
            get {
                return ResourceManager.GetString("CardMinersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Dungeon.
        /// </summary>
        public static string CardMinotaurDescription {
            get {
                return ResourceManager.GetString("CardMinotaurDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minotaur.
        /// </summary>
        public static string CardMinotaurName {
            get {
                return ResourceManager.GetString("CardMinotaurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +12 Wall.
        /// </summary>
        public static string CardMondoWallDescription {
            get {
                return ResourceManager.GetString("CardMondoWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mondo Wall.
        /// </summary>
        public static string CardMondoWallName {
            get {
                return ResourceManager.GetString("CardMondoWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 damage, you lose 3 Gems.
        /// </summary>
        public static string CardMoodyGoblinsDescription {
            get {
                return ResourceManager.GetString("CardMoodyGoblinsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moody Goblins.
        /// </summary>
        public static string CardMoodyGoblinsName {
            get {
                return ResourceManager.GetString("CardMoodyGoblinsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Quarry &lt; enemy Quarry, +2 Quarry, else +1 Quarry.
        /// </summary>
        public static string CardMotherLodeDescription {
            get {
                return ResourceManager.GetString("CardMotherLodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Lode.
        /// </summary>
        public static string CardMotherLodeName {
            get {
                return ResourceManager.GetString("CardMotherLodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Quarry.
        /// </summary>
        public static string CardNewEquipmentDescription {
            get {
                return ResourceManager.GetString("CardNewEquipmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Equipment.
        /// </summary>
        public static string CardNewEquipmentName {
            get {
                return ResourceManager.GetString("CardNewEquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 damage.
        /// </summary>
        public static string CardOgreDescription {
            get {
                return ResourceManager.GetString("CardOgreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogre.
        /// </summary>
        public static string CardOgreName {
            get {
                return ResourceManager.GetString("CardOgreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 damage.
        /// </summary>
        public static string CardOrcDescription {
            get {
                return ResourceManager.GetString("CardOrcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        public static string CardOrcName {
            get {
                return ResourceManager.GetString("CardOrcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All player&apos;s Magic equals the highest player&apos;s Magic.
        /// </summary>
        public static string CardParityDescription {
            get {
                return ResourceManager.GetString("CardParityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string CardParityName {
            get {
                return ResourceManager.GetString("CardParityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 Tower, +1 Magic.
        /// </summary>
        public static string CardPearlOfWisdomDescription {
            get {
                return ResourceManager.GetString("CardPearlOfWisdomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearl of Wisdom.
        /// </summary>
        public static string CardPearlOfWisdomName {
            get {
                return ResourceManager.GetString("CardPearlOfWisdomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 damage to enemy Tower.
        /// </summary>
        public static string CardPegasusLancerDescription {
            get {
                return ResourceManager.GetString("CardPegasusLancerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegasus Lancer.
        /// </summary>
        public static string CardPegasusLancerName {
            get {
                return ResourceManager.GetString("CardPegasusLancerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +13 Tower, +6 Recruits, +6 Bricks.
        /// </summary>
        public static string CardPhaseJewelDescription {
            get {
                return ResourceManager.GetString("CardPhaseJewelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Jewel.
        /// </summary>
        public static string CardPhaseJewelName {
            get {
                return ResourceManager.GetString("CardPhaseJewelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 Wall, +1 Dungeon.
        /// </summary>
        public static string CardPorticulusDescription {
            get {
                return ResourceManager.GetString("CardPorticulusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porticulus.
        /// </summary>
        public static string CardPorticulusName {
            get {
                return ResourceManager.GetString("CardPorticulusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 damage to your Tower, +2 Magic.
        /// </summary>
        public static string CardPowerBurnDescription {
            get {
                return ResourceManager.GetString("CardPowerBurnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Burn.
        /// </summary>
        public static string CardPowerBurnName {
            get {
                return ResourceManager.GetString("CardPowerBurnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw 1 card, discard 1 card, play again.
        /// </summary>
        public static string CardPrismDescription {
            get {
                return ResourceManager.GetString("CardPrismDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prism.
        /// </summary>
        public static string CardPrismName {
            get {
                return ResourceManager.GetString("CardPrismName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7 Tower, lose 10 Bricks.
        /// </summary>
        public static string CardQuarrysHelpDescription {
            get {
                return ResourceManager.GetString("CardQuarrysHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarry&apos;s Help.
        /// </summary>
        public static string CardQuarrysHelpName {
            get {
                return ResourceManager.GetString("CardQuarrysHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Tower, play again.
        /// </summary>
        public static string CardQuartzDescription {
            get {
                return ResourceManager.GetString("CardQuartzDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz.
        /// </summary>
        public static string CardQuartzName {
            get {
                return ResourceManager.GetString("CardQuartzName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 damage, enemy loses 3 Recruits.
        /// </summary>
        public static string CardRabidSheepDescription {
            get {
                return ResourceManager.GetString("CardRabidSheepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabid Sheep.
        /// </summary>
        public static string CardRabidSheepName {
            get {
                return ResourceManager.GetString("CardRabidSheepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Tower to all players, you gain 3 Gems.
        /// </summary>
        public static string CardRainbowDescription {
            get {
                return ResourceManager.GetString("CardRainbowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string CardRainbowName {
            get {
                return ResourceManager.GetString("CardRainbowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +8 Wall.
        /// </summary>
        public static string CardReinforcedWallDescription {
            get {
                return ResourceManager.GetString("CardReinforcedWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced Wall.
        /// </summary>
        public static string CardReinforcedWallName {
            get {
                return ResourceManager.GetString("CardReinforcedWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Wall, +1 Tower, +2 Recruits.
        /// </summary>
        public static string CardRockGardenDescription {
            get {
                return ResourceManager.GetString("CardRockGardenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Garden.
        /// </summary>
        public static string CardRockGardenName {
            get {
                return ResourceManager.GetString("CardRockGardenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +6 Wall, 10 damage to enemy.
        /// </summary>
        public static string CardRockLauncherDescription {
            get {
                return ResourceManager.GetString("CardRockLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Launcher.
        /// </summary>
        public static string CardRockLauncherName {
            get {
                return ResourceManager.GetString("CardRockLauncherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 damage, -1 enemy Quarry.
        /// </summary>
        public static string CardRockStompersDescription {
            get {
                return ResourceManager.GetString("CardRockStompersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Stompers.
        /// </summary>
        public static string CardRockStompersName {
            get {
                return ResourceManager.GetString("CardRockStompersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 Tower.
        /// </summary>
        public static string CardRubyDescription {
            get {
                return ResourceManager.GetString("CardRubyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby.
        /// </summary>
        public static string CardRubyName {
            get {
                return ResourceManager.GetString("CardRubyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +10 Tower, +5 Wall, gain 5 Recruits.
        /// </summary>
        public static string CardSanctuaryDescription {
            get {
                return ResourceManager.GetString("CardSanctuaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctuary.
        /// </summary>
        public static string CardSanctuaryName {
            get {
                return ResourceManager.GetString("CardSanctuaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +11 Tower.
        /// </summary>
        public static string CardSapphireDescription {
            get {
                return ResourceManager.GetString("CardSapphireDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapphire.
        /// </summary>
        public static string CardSapphireName {
            get {
                return ResourceManager.GetString("CardSapphireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Magic, play again.
        /// </summary>
        public static string CardSecretRoomDescription {
            get {
                return ResourceManager.GetString("CardSecretRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Room.
        /// </summary>
        public static string CardSecretRoomName {
            get {
                return ResourceManager.GetString("CardSecretRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 damage to enemy Tower, play again.
        /// </summary>
        public static string CardShadowFaerieDescription {
            get {
                return ResourceManager.GetString("CardShadowFaerieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Faerie.
        /// </summary>
        public static string CardShadowFaerieName {
            get {
                return ResourceManager.GetString("CardShadowFaerieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 Magic, 9 damage to enemy Tower.
        /// </summary>
        public static string CardShattererDescription {
            get {
                return ResourceManager.GetString("CardShattererDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shatterer.
        /// </summary>
        public static string CardShattererName {
            get {
                return ResourceManager.GetString("CardShattererName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch your Wall with enemy Wall.
        /// </summary>
        public static string CardShiftDescription {
            get {
                return ResourceManager.GetString("CardShiftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string CardShiftName {
            get {
                return ResourceManager.GetString("CardShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 damage.
        /// </summary>
        public static string CardSlasherDescription {
            get {
                return ResourceManager.GetString("CardSlasherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slasher.
        /// </summary>
        public static string CardSlasherName {
            get {
                return ResourceManager.GetString("CardSlasherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 damage to enemy Tower, play again.
        /// </summary>
        public static string CardSmokyQuartzDescription {
            get {
                return ResourceManager.GetString("CardSmokyQuartzDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoky Quartz.
        /// </summary>
        public static string CardSmokyQuartzName {
            get {
                return ResourceManager.GetString("CardSmokyQuartzName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Tower, +2 damage to enemy Tower.
        /// </summary>
        public static string CardSolarFlareDescription {
            get {
                return ResourceManager.GetString("CardSolarFlareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Flare.
        /// </summary>
        public static string CardSolarFlareName {
            get {
                return ResourceManager.GetString("CardSolarFlareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Wall &gt; enemy Wall, do 3 damage, else do 2 damage.
        /// </summary>
        public static string CardSpearmanDescription {
            get {
                return ResourceManager.GetString("CardSpearmanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spearman.
        /// </summary>
        public static string CardSpearmanName {
            get {
                return ResourceManager.GetString("CardSpearmanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Magic.
        /// </summary>
        public static string CardSpellWeaversDescription {
            get {
                return ResourceManager.GetString("CardSpellWeaversDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Weavers.
        /// </summary>
        public static string CardSpellWeaversName {
            get {
                return ResourceManager.GetString("CardSpellWeaversName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enemy Wall = 0, 10 damage, else 6 damage.
        /// </summary>
        public static string CardSpizzerDescription {
            get {
                return ResourceManager.GetString("CardSpizzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spizzer.
        /// </summary>
        public static string CardSpizzerName {
            get {
                return ResourceManager.GetString("CardSpizzerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 damage, +4 Wall.
        /// </summary>
        public static string CardStoneGiantDescription {
            get {
                return ResourceManager.GetString("CardStoneGiantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Giant.
        /// </summary>
        public static string CardStoneGiantName {
            get {
                return ResourceManager.GetString("CardStoneGiantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 Quarry, +10 Wall, you gain 5 Gems.
        /// </summary>
        public static string CardStripMineDescription {
            get {
                return ResourceManager.GetString("CardStripMineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip Mine.
        /// </summary>
        public static string CardStripMineName {
            get {
                return ResourceManager.GetString("CardStripMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4 Wall.
        /// </summary>
        public static string CardSturdyWallDescription {
            get {
                return ResourceManager.GetString("CardSturdyWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sturdy Wall.
        /// </summary>
        public static string CardSturdyWallName {
            get {
                return ResourceManager.GetString("CardSturdyWallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 damage to enemy Tower, enemy loses 8 Recruits.
        /// </summary>
        public static string CardSuccubusDescription {
            get {
                return ResourceManager.GetString("CardSuccubusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succubus.
        /// </summary>
        public static string CardSuccubusName {
            get {
                return ResourceManager.GetString("CardSuccubusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy loses 10 Gems, 5 Bricks, you gain 1/2 round up.
        /// </summary>
        public static string CardThiefDescription {
            get {
                return ResourceManager.GetString("CardThiefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        public static string CardThiefName {
            get {
                return ResourceManager.GetString("CardThiefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 damage, +4 Wall, +2 Tower.
        /// </summary>
        public static string CardTowerGremlinDescription {
            get {
                return ResourceManager.GetString("CardTowerGremlinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Gremlin.
        /// </summary>
        public static string CardTowerGremlinName {
            get {
                return ResourceManager.GetString("CardTowerGremlinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Walls take 5 damages, play again.
        /// </summary>
        public static string CardTremorsDescription {
            get {
                return ResourceManager.GetString("CardTremorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremors.
        /// </summary>
        public static string CardTremorsName {
            get {
                return ResourceManager.GetString("CardTremorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 Dungeon.
        /// </summary>
        public static string CardTrollTrainerDescription {
            get {
                return ResourceManager.GetString("CardTrollTrainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll Trainers.
        /// </summary>
        public static string CardTrollTrainerName {
            get {
                return ResourceManager.GetString("CardTrollTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Magic &gt; enemy Magic, 12 damage, else 8 damage.
        /// </summary>
        public static string CardUnicornDescription {
            get {
                return ResourceManager.GetString("CardUnicornDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicorn.
        /// </summary>
        public static string CardUnicornName {
            get {
                return ResourceManager.GetString("CardUnicornName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 damage, enemy loses 5 Recruits, -1 enemy Dungeon.
        /// </summary>
        public static string CardVampireDescription {
            get {
                return ResourceManager.GetString("CardVampireDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vampire.
        /// </summary>
        public static string CardVampireName {
            get {
                return ResourceManager.GetString("CardVampireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 damage, you lose 3 Gems.
        /// </summary>
        public static string CardWarlordDescription {
            get {
                return ResourceManager.GetString("CardWarlordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlord.
        /// </summary>
        public static string CardWarlordName {
            get {
                return ResourceManager.GetString("CardWarlordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 damage.
        /// </summary>
        public static string CardWerewolfDescription {
            get {
                return ResourceManager.GetString("CardWerewolfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werewolf.
        /// </summary>
        public static string CardWerewolfName {
            get {
                return ResourceManager.GetString("CardWerewolfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5 Wall, you lose 6 Gems.
        /// </summary>
        public static string CardWorkOvertimeDescription {
            get {
                return ResourceManager.GetString("CardWorkOvertimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Overtime.
        /// </summary>
        public static string CardWorkOvertimeName {
            get {
                return ResourceManager.GetString("CardWorkOvertimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string DeckClassicName {
            get {
                return ResourceManager.GetString("DeckClassicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        public static string DeckInfinityName {
            get {
                return ResourceManager.GetString("DeckInfinityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GameFinishedBackButtonText {
            get {
                return ResourceManager.GetString("GameFinishedBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play again.
        /// </summary>
        public static string GameFinishedPlayButtonText {
            get {
                return ResourceManager.GetString("GameFinishedPlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate resources.
        /// </summary>
        public static string GameFinishedResourcesAccumulateText {
            get {
                return ResourceManager.GetString("GameFinishedResourcesAccumulateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game finished.
        /// </summary>
        public static string GameFinishedText {
            get {
                return ResourceManager.GetString("GameFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build tower.
        /// </summary>
        public static string GameFinishedTowerBuildText {
            get {
                return ResourceManager.GetString("GameFinishedTowerBuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy tower.
        /// </summary>
        public static string GameFinishedTowerDestroyText {
            get {
                return ResourceManager.GetString("GameFinishedTowerDestroyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win {0}.
        /// </summary>
        public static string GameFinishedWinnerText {
            get {
                return ResourceManager.GetString("GameFinishedWinnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExitButtonText {
            get {
                return ResourceManager.GetString("MenuExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string MenuPlayButtonText {
            get {
                return ResourceManager.GetString("MenuPlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Capital.
        /// </summary>
        public static string RuleEmpireCapitalName {
            get {
                return ResourceManager.GetString("RuleEmpireCapitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiger&apos;s Lake.
        /// </summary>
        public static string RuleTigersLakeName {
            get {
                return ResourceManager.GetString("RuleTigersLakeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SettingsBackButtonText {
            get {
                return ResourceManager.GetString("SettingsBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string SettingsDeckText {
            get {
                return ResourceManager.GetString("SettingsDeckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string SettingsPlayButtonText {
            get {
                return ResourceManager.GetString("SettingsPlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string SettingsRuleText {
            get {
                return ResourceManager.GetString("SettingsRuleText", resourceCulture);
            }
        }
    }
}
